"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
interface Product { id: number|string; name:string; description:string|null; brand:string|null; category:string|null; hsn_code:string|null; status:"draft"|"active"|"archived"; }
export default function EditProductPage(){
 const params=useParams<{id:string}>(),router=useRouter(),productId=params?.id; const [product,setProduct]=useState<Product|null>(null); const [name,setName]=useState(""),[brand,setBrand]=useState(""),[category,setCategory]=useState(""),[hsnCode,setHsnCode]=useState(""),[description,setDescription]=useState(""),[status,setStatus]=useState<Product["status"]>("draft"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!productId)return;let cancelled=false;(async()=>{try{const r=await fetch(`/api/products/${productId}`),d=await r.json();if(!r.ok||!d.success)throw Error(d.error||"Failed to load product");if(cancelled)return;const p:Product=d.product;setProduct(p);setName(p.name||"");setBrand(p.brand||"");setCategory(p.category||"");setHsnCode(p.hsn_code||"");setDescription(p.description||"");setStatus(p.status);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Failed to load product");}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true}},[productId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!name.trim())return setError("Product name is required.");if(hsnCode.trim()&&!/^\d{4,8}$/.test(hsnCode.trim()))return setError("HSN code must contain 4 to 8 digits.");try{setSaving(true);const r=await fetch(`/api/products/${productId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),brand:brand.trim()||null,category:category.trim()||null,hsnCode:hsnCode.trim()||null,description:description.trim()||null,status})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.error||"Failed to update product");router.push(`/products/${productId}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setSaving(false)}}
 if(loading)return <div className="max-w-3xl mx-auto"><div className="bg-white border rounded-xl p-8 text-gray-500">Loading product...</div></div>; if(!product)return <div className="max-w-3xl mx-auto space-y-4"><Link href="/products" className="text-sm text-gray-500">← Products</Link><div className="bg-white border rounded-xl p-8 text-red-600">{error||"Product not found."}</div></div>;
 return <div className="max-w-3xl mx-auto"><div className="mb-8"><Link href={`/products/${productId}`} className="text-sm text-gray-500">← {product.name}</Link><h1 className="text-3xl font-bold mt-4">Edit Product</h1><p className="text-gray-500 mt-1">Update the canonical product information used across Dizito.</p></div><form onSubmit={submit} className="bg-white border rounded-xl p-6 md:p-8 space-y-6">{error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-lg px-4 py-3">{error}</div>}<div><label className="block text-sm font-medium mb-2">Product name</label><input value={name} onChange={e=>setName(e.target.value)} className="w-full border rounded-lg px-4 py-3"/></div><div className="grid md:grid-cols-2 gap-6"><div><label className="block text-sm font-medium mb-2">Brand</label><input value={brand} onChange={e=>setBrand(e.target.value)} className="w-full border rounded-lg px-4 py-3"/></div><div><label className="block text-sm font-medium mb-2">Category</label><input value={category} onChange={e=>setCategory(e.target.value)} className="w-full border rounded-lg px-4 py-3"/></div></div><div><label className="block text-sm font-medium mb-2">HSN code</label><input value={hsnCode} onChange={e=>setHsnCode(e.target.value.replace(/\D/g,"").slice(0,8))} inputMode="numeric" placeholder="4 to 8 digits" className="w-full border rounded-lg px-4 py-3"/><p className="text-xs text-gray-500 mt-1">Canonical product classification used by channels such as Amazon India. Enter only a verified HSN.</p></div><div><label className="block text-sm font-medium mb-2">Description</label><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={6} className="w-full border rounded-lg px-4 py-3"/></div><div><label className="block text-sm font-medium mb-2">Status</label><select value={status} onChange={e=>setStatus(e.target.value as Product["status"])} className="w-full border rounded-lg px-4 py-3 bg-white"><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></div><div className="flex justify-end gap-3 pt-4 border-t"><Link href={`/products/${productId}`} className="px-5 py-3 rounded-lg border">Cancel</Link><button type="submit" disabled={saving} className="bg-blue-600 text-white px-5 py-3 rounded-lg font-medium disabled:opacity-50">{saving?"Saving...":"Save Changes"}</button></div></form></div>;
}
