import { getAmazonMarketplaceId } from "@/lib/platforms/amazon/auth";
import { amazonSpApiRequest } from "@/lib/platforms/amazon/client";

export interface AmazonCatalogItemSummary { asin: string; itemName?: string | null; brand?: string | null; productType?: string | null; identifiers?: Array<{ identifier?: string; identifierType?: string; marketplaceId?: string }>; }
interface AmazonCatalogItemsResponse { items?: Array<{ asin?: string; summaries?: Array<{ itemName?: string; brandName?: string; productType?: string }>; productTypes?: Array<{ marketplaceId?: string; productType?: string }>; identifiers?: Array<{ marketplaceId?: string; identifiers?: Array<{ identifier?: string; identifierType?: string }> }> }>; }
function mapItems(data: AmazonCatalogItemsResponse): AmazonCatalogItemSummary[] { return (data.items ?? []).flatMap((item) => { if (!item.asin) return []; const summary = item.summaries?.[0]; const productType = item.productTypes?.find((entry) => entry.marketplaceId === getAmazonMarketplaceId())?.productType ?? summary?.productType; const ids = item.identifiers?.find((entry) => entry.marketplaceId === getAmazonMarketplaceId()); return [{ asin: item.asin, itemName: summary?.itemName ?? null, brand: summary?.brandName ?? null, productType: productType ?? null, identifiers: ids?.identifiers ?? [] }]; }); }
export async function searchAmazonCatalogByIdentifier(channelId: string, userId: number, identifier: string, identifierType: "EAN" | "UPC" | "GTIN" | "ISBN" | "ASIN") { const result = await amazonSpApiRequest<AmazonCatalogItemsResponse>(channelId, userId, { method: "GET", path: "/catalog/2022-04-01/items", query: { marketplaceIds: getAmazonMarketplaceId(), identifiers: identifier, identifiersType: identifierType, includedData: "summaries,identifiers,productTypes" } }); return { items: mapItems(result.data), requestId: result.requestId, rateLimit: result.rateLimit }; }
export async function searchAmazonCatalogByKeyword(channelId: string, userId: number, keywords: string) { const result = await amazonSpApiRequest<AmazonCatalogItemsResponse>(channelId, { method: "GET", path: "/catalog/2022-04-01/items", query: { marketplaceIds: getAmazonMarketplaceId(), keywords, includedData: "summaries,identifiers,productTypes" } }); return { items: mapItems(result.data), requestId: result.requestId, rateLimit: result.rateLimit }; }
function normalizeIsbn(value: string) { return value.replace(/[\s-]/g, "").toUpperCase(); }
function isValidIsbn10(value: string) { if (!/^(?:\d{9}[\dX])$/.test(value)) return false; return value.split("").reduce((sum, digit, index) => sum + (digit === "X" ? 10 : Number(digit)) * (10 - index), 0) % 11 === 0; }
function isValidIsbn13(value: string) { if (!/^\d{13}$/.test(value) || (!value.startsWith("978") && !value.startsWith("979"))) return false; const sum = value.slice(0, 12).split("").reduce((total, digit, index) => total + Number(digit) * (index % 2 === 0 ? 1 : 3), 0); return (10 - (sum % 10)) % 10 === Number(value[12]); }
export function identifierTypeForAmazonCatalog(identifier: string): "EAN" | "UPC" | "GTIN" | "ISBN" | null { const normalized = normalizeIsbn(identifier); if (isValidIsbn10(normalized) || isValidIsbn13(normalized)) return "ISBN"; if (/^\d{13}$/.test(normalized)) return "EAN"; if (/^\d{12}$/.test(normalized)) return "UPC"; if (/^\d{14}$/.test(normalized)) return "GTIN"; return null; }
export async function resolveAmazonCatalogIdentity(channelId: string, userId: number, identifier: string, expectedProductType: string) { const normalized = normalizeIsbn(identifier); const identifierType = identifierTypeForAmazonCatalog(normalized); if (!identifierType) return null; const result = await searchAmazonCatalogByIdentifier(channelId, userId, normalized, identifierType); const expected = expectedProductType.trim().toUpperCase(); const match = result.items.find((item) => item.productType?.trim().toUpperCase() === expected); return { asin: match?.asin ?? null, productType: match?.productType ?? null, identifierType, requestId: result.requestId, rateLimit: result.rateLimit }; }
