"use client";
import { useState } from "react";
import { Loader2, Sparkles } from "lucide-react";

type Optimization = { summary: string; opportunities: Array<{ action: string; rationale: string; campaignId: number | null; contentItemId: number | null; variantId: number | null; priority: string; observedOutcome: { actionType: string; count: number; value: number; platform: string | null } | null }>; experiments: Array<{ hypothesis: string; change: string; metric: string }>; measurement: Array<{ metric: string; reason: string }>; guardrails: string[] };

export default function AIOptimizerClient() {
  const [optimization, setOptimization] = useState<Optimization | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  function buildWeek() {    if (!optimization) return;    sessionStorage.setItem("dizito-optimizer-handoff", JSON.stringify(optimization));    window.location.href = "/generate-my-week?from=optimizer";  }  async function generate() {
    setLoading(true); setError("");
    try { const response = await fetch("/api/marketing/optimizer", { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to generate optimization"); setOptimization(data.optimization); }
    catch (err) { setError(err instanceof Error ? err.message : "Unable to generate optimization"); }
    finally { setLoading(false); }
  }
  return <main className="mx-auto max-w-6xl space-y-6 p-6">
    <header className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Sparkles size={22} /></div><div><p className="text-xs font-bold uppercase tracking-widest text-gray-500">AI Marketing Operator</p><h1 className="mt-1 text-2xl font-bold text-gray-900">AI Optimizer</h1><p className="mt-1 max-w-3xl text-sm text-gray-500">Learn from measured outcomes and explicit attribution to recommend what to improve next. Recommendations remain advisory.</p></div></div><button onClick={generate} disabled={loading} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{loading ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}{loading ? "Analyzing…" : "Generate Optimization"}</button>{optimization && <button onClick={buildWeek} className="ml-3 mt-5 inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold">Use for Next Week</button>}</header>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {optimization && <><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Optimization summary</h2><p className="mt-3 text-sm leading-6 text-gray-700">{optimization.summary}</p></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Opportunities</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{optimization.opportunities.map((item,index)=><article key={index} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{item.action}</strong><span className="text-xs uppercase text-gray-500">{item.priority}</span></div><p className="mt-1 text-sm text-gray-600">{item.rationale}</p><p className="mt-2 text-xs text-gray-500">{item.campaignId ? "Campaign #"+item.campaignId : "General"}{item.contentItemId ? " · Content #"+item.contentItemId : ""}{item.variantId ? " · Variant #"+item.variantId : ""}</p>{item.observedOutcome && <div className="mt-3 rounded-lg bg-gray-50 px-3 py-2 text-xs text-gray-600"><span className="font-semibold">Observed evidence:</span> {item.observedOutcome.count} {item.observedOutcome.actionType.replaceAll("_"," ")} action{item.observedOutcome.count === 1 ? "" : "s"} · value {item.observedOutcome.value}{item.observedOutcome.platform ? " · "+item.observedOutcome.platform : ""}<div className="mt-1 text-[11px] text-gray-500">Observed outcome only; not proof of causality.</div></div>}</article>)}</div></section>
      <section className="grid gap-6 md:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Experiments</h2><div className="mt-4 space-y-3">{optimization.experiments.map((item,index)=><div key={index} className="rounded-xl bg-gray-50 p-3"><div className="text-sm font-semibold">{item.hypothesis}</div><div className="mt-1 text-xs text-gray-600">Change: {item.change}</div><div className="mt-1 text-xs text-gray-600">Metric: {item.metric}</div></div>)}</div></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Measurement</h2><div className="mt-4 space-y-3">{optimization.measurement.map((item,index)=><div key={index} className="rounded-xl bg-gray-50 p-3"><div className="text-sm font-semibold">{item.metric}</div><div className="mt-1 text-xs text-gray-600">{item.reason}</div></div>)}</div></div></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Guardrails</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-gray-600">{optimization.guardrails.map((item,index)=><li key={index}>{item}</li>)}</ul></section>
    </>}
  </main>;
}