"use client";

import { useEffect, useState } from "react";
import { BarChart3, Loader2 } from "lucide-react";
import { DizitoButton, DizitoCard, DizitoPage, DizitoPageHeader, DizitoState } from "@/components/dizito/DizitoUI";

type Impact = {
  actionSummary: Array<{ actionType:string; count:number; value:number }>;
  observedCampaignSummary:Array<{campaignId:number|null;campaignName:string|null;actionType:string;count:number;value:number}>;
  attributionSummary:Array<{campaignId:number|null;campaignName:string|null;actionType:string;count:number;attributedValue:number}>;
  observedContentSummary:Array<{contentItemId:number|null;contentTopic:string|null;actionType:string;count:number;value:number}>;
  observedVariantSummary:Array<{variantId:number|null;contentItemId:number|null;platform:string|null;actionType:string;count:number;value:number}>;
  revenueSummary:{observedLinkedOrderCount:number;observedPurchaseValue:number;attributedOrderCount:number;attributedValue:number};
};

function label(value:string){ return value.replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase()); }

export default function BusinessImpactClient(){
 const [impact,setImpact]=useState<Impact|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 async function load(){try{setLoading(true);setError(null);const response=await fetch("/api/marketing/business-impact");const data=await response.json();if(!response.ok)throw new Error(data.error||"Failed to load business impact");if(!data.businessImpact)throw new Error("Unexpected business impact response");setImpact(data.businessImpact);}catch(e){setError(e instanceof Error?e.message:"Failed to load business impact");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 if(loading)return <DizitoPage><DizitoPageHeader eyebrow="Measure" title="Business Impact" description="Separate observed customer outcomes from explicitly attributed marketing outcomes."/><DizitoCard><div role="status" className="animate-pulse space-y-3"><div className="h-5 w-1/3 rounded bg-slate-100"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[0,1,2,3].map((item)=><div key={item} className="h-20 rounded-xl bg-slate-100"/> )}</div><div className="h-36 rounded-xl bg-slate-100"/></div></DizitoCard></DizitoPage>;
 if(error)return <DizitoPage><DizitoPageHeader eyebrow="Measure" title="Business Impact" description="Separate observed customer outcomes from explicitly attributed marketing outcomes."/><DizitoState kind="error" title="Business impact could not be loaded" description={error} action={<DizitoButton variant="secondary" onClick={() => void load()}>Try again</DizitoButton>}/></DizitoPage>;
 if(!impact)return <DizitoPage><DizitoState kind="empty" title="No business impact data" description="There is no business impact summary to display yet."/></DizitoPage>;
 return <div className="dizito-page space-y-5">
  <header className="dizito-card dizito-card-ai"><div className="flex items-start gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><BarChart3 size={22}/></div><div><h1 className="text-2xl font-bold text-gray-900">Business Impact</h1><p className="mt-1 text-sm text-gray-500">Separate observed customer outcomes from explicitly attributed marketing outcomes.</p></div></div></header>
  <section className="grid gap-4 md:grid-cols-4">
   <div className="dizito-metric"><div className="text-sm text-gray-500">Observed linked orders</div><div className="mt-2 text-3xl font-bold">{impact.revenueSummary.observedLinkedOrderCount}</div></div>
   <div className="dizito-metric"><div className="text-sm text-gray-500">Observed purchase value</div><div className="mt-2 text-3xl font-bold">{impact.revenueSummary.observedPurchaseValue}</div></div>
   <div className="dizito-metric"><div className="text-sm text-gray-500">Explicitly attributed orders</div><div className="mt-2 text-3xl font-bold">{impact.revenueSummary.attributedOrderCount}</div></div>
   <div className="dizito-metric"><div className="text-sm text-gray-500">Explicitly attributed value</div><div className="mt-2 text-3xl font-bold">{impact.revenueSummary.attributedValue}</div></div>
  </section>
  <section className="dizito-card"><h2 className="text-lg font-semibold">Customer actions</h2><div className="mt-4 divide-y">{impact.actionSummary.length===0?<p className="py-6 text-sm text-gray-500">No completed customer actions yet.</p>:impact.actionSummary.map(a=><div key={a.actionType} className="flex items-center justify-between py-3"><span className="text-sm font-medium">{label(a.actionType)}</span><span className="text-sm text-gray-600">{a.count} · value {a.value}</span></div>)}</div></section>
  <section className="dizito-card"><h2 className="text-lg font-semibold">Observed content outcomes</h2><p className="mt-1 text-sm text-gray-500">Completed customer actions linked to Content Items. These are observed outcomes, not content performance scores or causal attribution.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-gray-500"><th className="py-2 pr-4">Content Item</th><th className="py-2 pr-4">Action</th><th className="py-2 pr-4">Count</th><th className="py-2">Observed value</th></tr></thead><tbody>{impact.observedContentSummary.length===0?<tr><td colSpan={4} className="py-6 text-gray-500">No content-linked customer actions yet.</td></tr>:impact.observedContentSummary.map((a,i)=><tr key={`content-${a.contentItemId}-${a.actionType}-${i}`} className="border-b last:border-0"><td className="py-3 pr-4 font-medium">{a.contentTopic||`Content Item #${a.contentItemId ?? "Unassigned"}`}</td><td className="py-3 pr-4">{label(a.actionType)}</td><td className="py-3 pr-4">{a.count}</td><td className="py-3">{a.value}</td></tr>)}</tbody></table></div></section>
  <section className="dizito-card"><h2 className="text-lg font-semibold">Observed variant outcomes</h2><p className="mt-1 text-sm text-gray-500">Completed customer actions linked to channel variants. Use these as evidence for optimization, not proof that a variant caused the result.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-gray-500"><th className="py-2 pr-4">Variant</th><th className="py-2 pr-4">Platform</th><th className="py-2 pr-4">Action</th><th className="py-2 pr-4">Count</th><th className="py-2">Observed value</th></tr></thead><tbody>{impact.observedVariantSummary.length===0?<tr><td colSpan={5} className="py-6 text-gray-500">No variant-linked customer actions yet.</td></tr>:impact.observedVariantSummary.map((a,i)=><tr key={`variant-${a.variantId}-${a.actionType}-${i}`} className="border-b last:border-0"><td className="py-3 pr-4 font-medium">Variant #{a.variantId ?? "Unassigned"}</td><td className="py-3 pr-4">{a.platform?label(a.platform):"Unknown"}</td><td className="py-3 pr-4">{label(a.actionType)}</td><td className="py-3 pr-4">{a.count}</td><td className="py-3">{a.value}</td></tr>)}</tbody></table></div></section>
  <section className="dizito-card"><h2 className="text-lg font-semibold">Explicit attribution</h2><p className="mt-1 text-sm text-gray-500">Only attribution records explicitly attached to a customer action are shown here. This does not infer causality.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-gray-500"><th className="py-2 pr-4">Campaign</th><th className="py-2 pr-4">Action</th><th className="py-2 pr-4">Attributions</th><th className="py-2">Attributed value</th></tr></thead><tbody>{impact.attributionSummary.length===0?<tr><td colSpan={4} className="py-6 text-gray-500">No explicit attribution records yet.</td></tr>:impact.attributionSummary.map((a,i)=><tr key={`${a.campaignId}-${a.actionType}-${i}`} className="border-b last:border-0"><td className="py-3 pr-4 font-medium">{a.campaignName||`Campaign #${a.campaignId ?? "Unassigned"}`}</td><td className="py-3 pr-4">{label(a.actionType)}</td><td className="py-3 pr-4">{a.count}</td><td className="py-3">{a.attributedValue}</td></tr>)}</tbody></table></div></section>
  <section className="dizito-card"><h2 className="text-lg font-semibold">Observed campaign outcomes</h2><p className="mt-1 text-sm text-gray-500">Customer actions linked to campaigns are observations, not attribution.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-gray-500"><th className="py-2 pr-4">Campaign</th><th className="py-2 pr-4">Action</th><th className="py-2 pr-4">Count</th><th className="py-2">Value</th></tr></thead><tbody>{impact.observedCampaignSummary.length===0?<tr><td colSpan={4} className="py-6 text-gray-500">No campaign-linked actions yet.</td></tr>:impact.observedCampaignSummary.map((a,i)=><tr key={`${a.campaignId}-${a.actionType}-${i}`} className="border-b last:border-0"><td className="py-3 pr-4 font-medium">{a.campaignName||`Campaign #${a.campaignId}`}</td><td className="py-3 pr-4">{label(a.actionType)}</td><td className="py-3 pr-4">{a.count}</td><td className="py-3">{a.value}</td></tr>)}</tbody></table></div></section>
 </div>;
}
