"use client";

import { useEffect, useState } from "react";
import { DizitoBadge, DizitoCard, DizitoPage, DizitoPageHeader, DizitoState, DizitoButton } from "@/components/dizito/DizitoUI";

type ConnectedAccount={id:number;platform:string;account_name:string;status:string};
type SettingsResponse={account:{id:number;name:string;email:string};subscription:{plan:string;status:string;subscriptionId:string|null;currentPeriodStart:string|null;currentPeriodEnd:string|null;trialEnd:string|null;cancelAtPeriodEnd:boolean};connectedAccounts:ConnectedAccount[];preferences:{emailNotifications:boolean;publishSuccess:boolean;publishFailure:boolean}};

export default function SettingsPage(){
 const [settings,setSettings]=useState<SettingsResponse|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/settings");const d=await r.json();if(r.ok)setSettings(d);}catch(error){console.error(error);}finally{setLoading(false);}})();},[]);
 if(loading)return <DizitoPage><DizitoState kind="empty" title="Loading settings" description="Preparing your account configuration." /></DizitoPage>;
 if(!settings)return <DizitoPage><DizitoState kind="error" title="Settings could not be loaded" description="We could not retrieve your account settings. Refresh and try again."/></DizitoPage>;
 const s=settings.subscription,plan=s.plan;
 const upgradeLabel=plan==="free"?"Upgrade":plan==="creator"?"Upgrade to Agency":"Current Plan";
 const statusTone=s.status==="active"?"success":s.status==="trialing"?"ai":s.status==="past_due"||s.status==="cancelled"?"warning":"neutral";
 return <DizitoPage><DizitoPageHeader eyebrow="Account" title="Settings" description="Manage your Dizito account, subscription visibility, connected accounts, and notification preferences."/>
  <div className="grid gap-5 lg:grid-cols-2">
   <DizitoCard className="p-5 md:p-6"><h2 className="text-lg font-semibold">Account</h2><p className="mt-1 text-sm text-gray-500">Your current account identity.</p><div className="mt-5 space-y-4">{[["Name",settings.account.name],["Email",settings.account.email]].map(([label,value])=><div key={label}><label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-gray-400">{label}</label><div className="rounded-xl border bg-gray-50 px-4 py-3 text-sm text-gray-700">{value}</div></div>)}</div></DizitoCard>
   <DizitoCard className="p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Subscription</h2><p className="mt-1 text-sm text-gray-500">Current plan and billing status.</p></div><DizitoBadge tone={statusTone}>{s.status}</DizitoBadge></div><div className="mt-5 space-y-3 text-sm">{[["Plan",plan],...(s.currentPeriodEnd?[["Next Billing",new Date(s.currentPeriodEnd).toLocaleDateString()] as [string,string]]:[]),...(s.trialEnd?[["Trial Ends",new Date(s.trialEnd).toLocaleDateString()] as [string,string]]:[]),...(s.subscriptionId?[["Subscription ID",s.subscriptionId] as [string,string]]:[])].map(([label,value])=><div key={label} className="flex flex-col gap-1 border-b pb-3 last:border-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><span className="text-gray-500">{label}</span><span className={label==="Subscription ID"?"break-all font-mono text-xs":"font-medium capitalize"}>{value}</span></div>)}</div><DizitoButton className="mt-5" disabled={plan==="agency"}>{upgradeLabel}</DizitoButton></DizitoCard>
   <DizitoCard className="p-5 md:p-6"><h2 className="text-lg font-semibold">Connected Accounts</h2><p className="mt-1 text-sm text-gray-500">Connected distribution identities visible to this account.</p>{settings.connectedAccounts.length===0?<div className="mt-5"><DizitoState kind="empty" title="No accounts connected" description="Connect a channel from Channels & Accounts."/></div>:<div className="mt-5 space-y-3">{settings.connectedAccounts.map(a=><div key={a.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-medium capitalize">{a.platform}</div><div className="mt-1 text-sm text-gray-500">{a.account_name}</div></div><DizitoBadge tone={a.status==="connected"?"success":"warning"}>{a.status}</DizitoBadge></div>)}</div>}</DizitoCard>
   <DizitoCard className="p-5 md:p-6"><h2 className="text-lg font-semibold">Preferences</h2><p className="mt-1 text-sm text-gray-500">Current notification preferences. Editing remains outside this surface.</p><div className="mt-5 space-y-3">{[["Email Notifications",settings.preferences.emailNotifications],["Publish Success",settings.preferences.publishSuccess],["Publish Failure",settings.preferences.publishFailure]].map(([label,value])=><div key={label as string} className="flex items-center justify-between gap-4 rounded-xl border p-4"><span className="text-sm font-medium">{label as string}</span><DizitoBadge tone={value?"success":"neutral"}>{value?"On":"Off"}</DizitoBadge></div>)}</div></DizitoCard>
  </div>
  <DizitoCard className="mt-5 border-red-200 p-5 md:p-6"><h2 className="text-lg font-semibold text-red-700">Danger Zone</h2><p className="mt-2 text-sm text-gray-600">Account deletion is a destructive operation. The current UI does not attach a deletion workflow here.</p><DizitoButton variant="danger" className="mt-4" disabled>Delete Account</DizitoButton></DizitoCard>
 </DizitoPage>;
}